web: gunicorn apptech:app

worker: gunicorn GetCustomerDetails.py
worker: gunicorn GetCustomerDetailsAll.py
worker: gunicorn GetBookedAppointmentSlot.py
worker: gunicorn QueryBusinessPrimaryData.py
worker: gunicorn Update.py
worker: gunicorn UpdateCustomerStatus.py
worker: gunicorn UpdateCustomerFeedback.py
worker: gunicorn QueryBusinessDetailsData.py
worker: gunicorn GetAppointmentSchedule.py
worker: gunicorn GetLastCheckedoutTokenNum.py
worker: gunicorn GetLiveFeed.py
worker: gunicorn TokenNumberGeneration.py
worker: gunicorn InsertBusinessPrimaryData.py
worker: gunicorn InsertBusinessDetailsData.py
worker: gunicorn QueryBusinessPrimaryAll.py
worker: gunicorn AverageWaitTime.py
worker: gunicorn GetCustomerBusinessDetails.py
worker: gunicorn AppointmentChatbots.py
worker: gunicorn weather.py
worker: gunicorn UpdateBusinessPrimaryData.py